<?php
/**
 * @file
 * field.entityform.field_image_custom_achievement.war_zone_grant_achievement.inc
 */

$api = '2.0.0';

$data = array(
  'field_config' => array(
    'entity_types' => array(),
    'foreign keys' => array(),
    'indexes' => array(
      'value' => array(
        0 => 'value',
      ),
    ),
    'settings' => array(
      'allowed_values' => array(
        0 => 'First Place',
        1 => 'Second Place',
        2 => 'Third Place',
        3 => 'Star and Crown',
        4 => 'General',
        5 => 'Campaign Badge',
      ),
      'allowed_values_function' => '',
      'profile2_private' => FALSE,
    ),
    'translatable' => '0',
    'storage' => array(
      'type' => 'field_sql_storage',
      'settings' => array(),
      'module' => 'field_sql_storage',
      'active' => '1',
      'details' => array(
        'sql' => array(
          'FIELD_LOAD_CURRENT' => array(
            'field_data_field_image_custom_achievement' => array(
              'value' => 'field_image_custom_achievement_value',
            ),
          ),
          'FIELD_LOAD_REVISION' => array(
            'field_revision_field_image_custom_achievement' => array(
              'value' => 'field_image_custom_achievement_value',
            ),
          ),
        ),
      ),
    ),
    'field_name' => 'field_image_custom_achievement',
    'type' => 'list_integer',
    'module' => 'list',
    'active' => '1',
    'locked' => '0',
    'cardinality' => '1',
    'deleted' => '0',
    'columns' => array(
      'value' => array(
        'type' => 'int',
        'not null' => FALSE,
      ),
    ),
  ),
  'field_instance' => array(
    'default_value' => NULL,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 5,
      ),
    ),
    'label' => 'Badge',
    'required' => 1,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'content_taxonomy_opt_groups' => FALSE,
      ),
      'type' => 'options_select',
      'weight' => 3,
    ),
    'field_name' => 'field_image_custom_achievement',
    'entity_type' => 'entityform',
    'bundle' => 'war_zone_grant_achievement',
    'deleted' => '0',
  ),
);

$dependencies = array();

$optional = array();

$modules = array(
  0 => 'field_sql_storage',
  1 => 'list',
  2 => 'options',
);
