<?php
// Plugin definition
$plugin = array(
  'title' => t('Bootopoly its'),
  'icon' => 'bootopoly-its.png',
  'category' => t('Bootopoly'),
  'theme' => 'bootopoly_its',
  'regions' => array(
    'header' => t('Header'),
    'sidebar' => t('Content Sidebar'),
    'contentmaintop' => t('Content Top'),
    'contentmainbottom' => t('Content Bottom'),
    'contentmainright' => t('Content Right'),
    'contentmainleft' => t('Content Left'),
    'footer' => t('Footer'),
  ),
);
